version: 2
jobs:
  build:
    working_direcotry: /home/app/webapp/
    docker:
      -image: docker:17.05.0-ce-git
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compoase==1.15.0
          # This assumes pytest is installed via the install-package step above
      - run:
          name: Test Cases
          command: |
            docker-compose up -d
            docker-compose run parking_api python manage.py test.py

      - docker-test:
          name: Check Docker deamon status
          command: docker info
      - deploy:
          name: Push application Docker Image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker build -t parking_api .
            docker push parking_api:latest
