# Generated by Django 4.2.2 on 2023-06-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="bookinh_plate", new_name="booking_date",
        ),
    ]
