# Generated by Django 4.2.2 on 2023-06-19 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_rename_bookinh_plate_booking_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
